Updated working .init

diff --git a/patriotctf/breakfastclub/.init b/patriotctf/breakfastclub/.init
--- a/patriotctf/breakfastclub/.init
+++ b/patriotctf/breakfastclub/.init
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-exec > logfile.log 2>&1
-echo "Running .init script" >> /tmp/.dojo/entrypoint.log
-ln -sf /flag flag.txt
-echo "Running .init script" >> /tmp/.dojo/entrypoint.log
+# Attempt to create a symbolic link
+ln -s /flag /challenge/flag.txt 2>/dev/null
+# if [ $? -eq 0 ]; then
+#     echo "$(date) - Symbolic link from /flag to /challenge/flag.txt created successfully" >> "$LOG_FILE"
+# else
+#     echo "$(date) - Failed to create symbolic link from /flag to /challenge/flag.txt" >> "$LOG_FILE"
+# fi
